# Setup
title:               Marble Cake Gov

tagline:             ''
description:         'A blog about public sector tech in multi-layered democracy.
                     Made by <a href="https://twitter.com/alexsoble">@alexsoble</a>.'

url:                 https://alexsoble.github.io/marble-cake-blog

baseurl:             ''

paginate:            5

permalink:           pretty

# About/contact
author:
  name:              Alex Soble
  url:               https://twitter.com/alexsoble
  email:             none

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

google_analytics_id: #UA-XXXX-Y
